# Generated by Django 2.2.5 on 2019-10-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
